# Generated by Django 2.0.6 on 2018-07-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffinfo',
            name='qrcode',
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='staff_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
